services:
  whatsapp-api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MONGO_URL: "${MONGO_URL}"
        API_PORT: "${API_PORT}"
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - MONGO_URL=aa
      - API_PORT=3001
