services:
  rr-whatsapp-api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./index.js:/opt/RR-WhatsApp-API/index.js
    ports:
      - "${WEB_PORT}:3001"
      - "${API_PORT}:8080"
